#!/usr/bin/env python3
"""Build the curated PyPI seed list used by generate_index.py."""

import json
from pathlib import Path


# (pypi_name, [tags])
SEEDS = [
    ("requests", ["HTTP", "客户端"]),
    ("urllib3", ["HTTP", "客户端"]),
    ("httpx", ["HTTP", "异步", "客户端"]),
    ("aiohttp", ["HTTP", "异步"]),
    ("httpcore", ["HTTP", "异步"]),
    ("h11", ["HTTP", "协议"]),
    ("anyio", ["异步", "并发"]),
    ("sniffio", ["异步"]),
    ("multidict", ["HTTP", "数据结构"]),
    ("yarl", ["URL", "解析"]),
    ("frozenlist", ["数据结构"]),
    ("idna", ["编码", "国际化"]),
    ("chardet", ["编码", "字符集"]),
    ("charset-normalizer", ["编码", "字符集"]),
    ("certifi", ["TLS", "证书"]),
    ("Flask", ["Web框架", "WSGI"]),
    ("Werkzeug", ["WSGI", "工具库"]),
    ("Jinja2", ["模板引擎"]),
    ("MarkupSafe", ["安全", "模板"]),
    ("click", ["命令行", "CLI"]),
    ("itsdangerous", ["安全", "签名"]),
    ("blinker", ["事件", "信号"]),
    ("Django", ["Web框架", "ORM"]),
    ("djangorestframework", ["Web框架", "REST"]),
    ("django-cors-headers", ["Web", "CORS"]),
    ("django-filter", ["Web", "查询"]),
    ("django-environ", ["配置", "环境变量"]),
    ("FastAPI", ["Web框架", "异步"]),
    ("starlette", ["Web框架", "异步"]),
    ("uvicorn", ["服务器", "ASGI"]),
    ("gunicorn", ["服务器", "WSGI"]),
    ("waitress", ["服务器", "WSGI"]),
    ("tornado", ["Web框架", "异步"]),
    ("sanic", ["Web框架", "异步"]),
    ("quart", ["Web框架", "异步"]),
    ("Bottle", ["Web框架", "WSGI"]),
    ("web.py", ["Web框架"]),
    ("aiofiles", ["文件", "异步"]),
    ("beautifulsoup4", ["HTML", "解析", "爬虫"]),
    ("bs4", ["HTML", "解析"]),
    ("lxml", ["XML", "HTML", "解析"]),
    ("html5lib", ["HTML", "解析"]),
    ("pyquery", ["HTML", "解析"]),
    ("feedparser", ["RSS", "解析"]),
    ("Scrapy", ["爬虫", "Web"]),
    ("selenium", ["浏览器自动化", "测试"]),
    ("playwright", ["浏览器自动化", "测试"]),
    ("pyppeteer", ["浏览器自动化", "爬虫"]),
    ("pytest", ["测试", "断言"]),
    ("pytest-cov", ["测试", "覆盖率"]),
    ("pytest-asyncio", ["测试", "异步"]),
    ("pytest-xdist", ["测试", "并行"]),
    ("pytest-mock", ["测试", "Mock"]),
    ("pytest-timeout", ["测试"]),
    ("coverage", ["测试", "覆盖率"]),
    ("hypothesis", ["测试", "属性测试"]),
    ("freezegun", ["测试", "时间"]),
    ("responses", ["测试", "HTTP Mock"]),
    ("moto", ["测试", "云服务 Mock"]),
    ("tox", ["测试", "虚拟环境"]),
    ("nox", ["测试", "自动化"]),
    ("unittest2", ["测试"]),
    ("mock", ["测试", "Mock"]),
    ("black", ["格式化", "代码质量"]),
    ("isort", ["导入排序", "代码质量"]),
    ("ruff", ["Lint", "代码质量"]),
    ("flake8", ["Lint", "代码质量"]),
    ("pylint", ["Lint", "代码质量"]),
    ("autopep8", ["格式化", "代码质量"]),
    ("mypy", ["类型检查"]),
    ("pyright", ["类型检查"]),
    ("pre-commit", ["Git", "钩子"]),
    ("SQLAlchemy", ["ORM", "数据库"]),
    ("SQLModel", ["ORM", "数据库"]),
    ("Alembic", ["数据库迁移"]),
    ("psycopg2-binary", ["数据库驱动", "PostgreSQL"]),
    ("psycopg", ["数据库驱动", "PostgreSQL", "异步"]),
    ("asyncpg", ["数据库驱动", "PostgreSQL", "异步"]),
    ("PyMySQL", ["数据库驱动", "MySQL"]),
    ("mysqlclient", ["数据库驱动", "MySQL"]),
    ("aiomysql", ["数据库驱动", "MySQL", "异步"]),
    ("sqlite-utils", ["数据库", "SQLite"]),
    ("Peewee", ["ORM", "数据库"]),
    ("pony", ["ORM", "数据库"]),
    ("dataset", ["数据库", "工具库"]),
    ("records", ["数据库", "SQL"]),
    ("pymongo", ["NoSQL", "MongoDB"]),
    ("motor", ["NoSQL", "MongoDB", "异步"]),
    ("redis", ["NoSQL", "Redis", "缓存"]),
    ("fakeredis", ["NoSQL", "Redis", "测试"]),
    ("hiredis", ["NoSQL", "Redis", "协议"]),
    ("pydantic", ["数据校验", "序列化"]),
    ("pydantic-core", ["数据校验", "核心"]),
    ("marshmallow", ["序列化", "校验"]),
    ("attrs", ["类", "工具库"]),
    ("dataclasses", ["标准库", "数据类"]),
    ("numpy", ["科学计算", "数组"]),
    ("pandas", ["数据分析", "表格"]),
    ("polars", ["数据分析", "列式"]),
    ("pyarrow", ["列式存储", "大数据"]),
    ("scipy", ["科学计算", "算法"]),
    ("scikit-learn", ["机器学习", "算法"]),
    ("scikit-image", ["图像处理", "算法"]),
    ("matplotlib", ["可视化", "绘图"]),
    ("seaborn", ["可视化", "统计"]),
    ("plotly", ["可视化", "交互"]),
    ("bokeh", ["可视化", "交互"]),
    ("xarray", ["科学计算", "多维数组"]),
    ("numba", ["JIT", "科学计算"]),
    ("sympy", ["符号计算", "数学"]),
    ("statsmodels", ["统计", "模型"]),
    ("openpyxl", ["Excel", "Office"]),
    ("xlrd", ["Excel", "解析"]),
    ("xlsxwriter", ["Excel", "Office"]),
    ("reportlab", ["PDF", "文档"]),
    ("pypdf", ["PDF", "解析"]),
    ("PyPDF2", ["PDF", "解析"]),
    ("pdfplumber", ["PDF", "解析"]),
    ("fpdf2", ["PDF", "生成"]),
    ("python-docx", ["Word", "文档"]),
    ("Pillow", ["图像处理", "图片"]),
    ("opencv-python", ["图像处理", "计算机视觉"]),
    ("imageio", ["图像", "IO"]),
    ("scikit-image", ["图像处理", "算法"]),
    ("torch", ["深度学习", "张量"]),
    ("torchvision", ["深度学习", "计算机视觉"]),
    ("tensorflow", ["深度学习", "机器学习"]),
    ("keras", ["深度学习", "机器学习"]),
    ("transformers", ["自然语言处理", "模型"]),
    ("tokenizers", ["自然语言处理", "分词"]),
    ("accelerate", ["深度学习", "训练"]),
    ("datasets", ["数据集", "机器学习"]),
    ("xgboost", ["机器学习", "梯度提升"]),
    ("lightgbm", ["机器学习", "梯度提升"]),
    ("catboost", ["机器学习", "梯度提升"]),
    ("shap", ["机器学习", "可解释性"]),
    ("jax", ["深度学习", "自动微分"]),
    ("jaxlib", ["深度学习", "运行时"]),
    ("gymnasium", ["强化学习", "环境"]),
    ("stable-baselines3", ["强化学习", "算法"]),
    ("networkx", ["图算法", "网络"]),
    ("nltk", ["自然语言处理", "文本"]),
    ("spacy", ["自然语言处理", "文本"]),
    ("gensim", ["自然语言处理", "主题模型"]),
    ("langchain", ["自然语言处理", "Agent"]),
    ("langchain-core", ["自然语言处理", "核心"]),
    ("openai", ["AI", "API客户端"]),
    ("anthropic", ["AI", "API客户端"]),
    ("tiktoken", ["分词", "AI"]),
    ("cryptography", ["加密", "安全"]),
    ("pycryptodome", ["加密", "安全"]),
    ("bcrypt", ["密码哈希", "安全"]),
    ("passlib", ["密码哈希", "安全"]),
    ("PyJWT", ["JWT", "安全"]),
    ("python-jose", ["JWT", "安全"]),
    ("oauthlib", ["OAuth", "安全"]),
    ("requests-oauthlib", ["OAuth", "HTTP"]),
    ("google-auth", ["OAuth", "认证"]),
    ("authlib", ["OAuth", "认证"]),
    ("python-dotenv", ["配置", "环境变量"]),
    ("dynaconf", ["配置", "环境变量"]),
    ("pydantic-settings", ["配置", "环境变量"]),
    ("pyyaml", ["YAML", "解析"]),
    ("tomli", ["TOML", "解析"]),
    ("tomli-w", ["TOML", "生成"]),
    ("orjson", ["JSON", "高性能"]),
    ("ujson", ["JSON", "高性能"]),
    ("python-rapidjson", ["JSON", "高性能"]),
    ("msgpack", ["序列化", "二进制"]),
    ("protobuf", ["序列化", "RPC"]),
    ("grpcio", ["RPC", "gRPC"]),
    ("grpcio-tools", ["RPC", "代码生成"]),
    ("thrift", ["RPC", "序列化"]),
    ("avro", ["序列化", "大数据"]),
    ("paho-mqtt", ["MQTT", "消息队列"]),
    ("aio-mqtt", ["MQTT", "消息队列"]),
    ("pika", ["AMQP", "消息队列"]),
    ("kombu", ["消息队列", "AMQP"]),
    ("celery", ["任务队列", "异步"]),
    ("kafka-python", ["Kafka", "消息队列"]),
    ("confluent-kafka", ["Kafka", "消息队列"]),
    ("aiokafka", ["Kafka", "消息队列"]),
    ("pulsar-client", ["消息队列", "流计算"]),
    ("nats-py", ["消息队列", "NATS"]),
    ("pyzmq", ["消息队列", "ZeroMQ"]),
    ("websockets", ["WebSocket", "网络"]),
    ("boto3", ["云服务", "AWS"]),
    ("botocore", ["云服务", "AWS"]),
    ("google-cloud-storage", ["云存储", "GCP"]),
    ("google-api-python-client", ["API客户端", "GCP"]),
    ("azure-storage-blob", ["云存储", "Azure"]),
    ("azure-identity", ["认证", "Azure"]),
    ("kubernetes", ["云原生", "Kubernetes"]),
    ("docker", ["容器", "Docker"]),
    ("paramiko", ["SSH", "网络"]),
    ("fabric", ["运维", "SSH"]),
    ("ansible", ["运维", "自动化"]),
    ("psutil", ["系统信息", "监控"]),
    ("pyinstaller", ["打包", "可执行文件"]),
    ("virtualenv", ["虚拟环境", "工具"]),
    ("pipenv", ["依赖管理", "虚拟环境"]),
    ("poetry-core", ["依赖管理", "构建"]),
    ("hatchling", ["构建", "打包"]),
    ("setuptools", ["构建", "打包"]),
    ("wheel", ["构建", "打包"]),
    ("twine", ["发布", "PyPI"]),
    ("pip-tools", ["依赖管理"]),
    ("rich", ["终端", "格式化"]),
    ("textual", ["终端", "TUI"]),
    ("prompt_toolkit", ["终端", "交互"]),
    ("questionary", ["终端", "交互"]),
    ("colorama", ["终端", "颜色"]),
    ("pygments", ["代码高亮", "终端"]),
    ("watchdog", ["文件监听", "工具"]),
    ("tenacity", ["重试", "容错"]),
    ("more-itertools", ["迭代器", "工具库"]),
    ("boltons", ["工具库", "标准库补充"]),
    ("humanize", ["格式化", "工具库"]),
    ("python-dateutil", ["日期时间", "解析"]),
    ("pytz", ["时区", "日期时间"]),
    ("pendulum", ["日期时间", "时区"]),
    ("arrow", ["日期时间", "工具库"]),
    ("pytest-html", ["测试", "报告"]),
    ("allure-pytest", ["测试", "报告"]),
    ("pandas-gbq", ["数据分析", "BigQuery"]),
    ("geopandas", ["地理信息", "数据分析"]),
    ("shapely", ["地理信息", "几何"]),
    ("fiona", ["地理信息", "矢量"]),
    ("pyproj", ["地理信息", "投影"]),
    ("rasterio", ["地理信息", "栅格"]),
    ("folium", ["地图", "可视化"]),
    ("tqdm", ["进度条", "工具"]),
    ("pygame", ["游戏开发", "多媒体"]),
    ("arcade", ["游戏开发", "2D"]),
    ("camelot", ["PDF", "表格提取"]),
    ("tabula-py", ["PDF", "表格提取"]),
]


def main() -> int:
    out = Path(__file__).resolve().parent.parent / "tools" / "seeds"
    out.mkdir(parents=True, exist_ok=True)
    data = [{"name": name, "tags": tags} for name, tags in SEEDS]
    (out / "python.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(data)} seeds to {out / 'python.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
